---
# Run this commands to get make a diff of settings
#   gsettings list-recursively > original.txt
#   diff <(cat original.txt) <(gsettings list-recursively)

- name: Set global keybindings
  command: "{{ item }}"
  with_items:
    - gsettings set org.gnome.desktop.wm.keybindings switch-input-source "[]"
    - gsettings set org.gnome.desktop.wm.keybindings switch-input-source-backward "[]"

- name: Set workspaces preferences
  command: "{{ item }}"
  with_items:
    - gsettings set org.compiz.core:/org/compiz/profiles/unity/plugins/core/ hsize 2
    - gsettings set org.compiz.core:/org/compiz/profiles/unity/plugins/core/ vsize 2
    - gsettings set org.gnome.desktop.wm.preferences num-workspaces 4

- name: Set Nautilus preferences
  command: "{{ item }}"
  with_items:
    - gsettings set org.gnome.nautilus.preferences default-folder-viewer 'list-view'
    - gsettings set org.gnome.nautilus.icon-view default-zoom-level 'smaller'
    - gsettings set org.gnome.nautilus.list-view default-zoom-level 'smaller'
    - gsettings set org.gnome.nautilus.list-view use-tree-view true
    - gsettings set org.gnome.nautilus.preferences thumbnail-limit "uint64 5242880"
    - gsettings set org.gnome.nautilus.icon-view thumbnail-size 64
    - gsettings set org.compiz.unityshell:/org/compiz/profiles/unity/plugins/unityshell/ icon-size 24

- name: Set Gedit preferences
  command: "{{ item }}"
  with_items:
    - gsettings set org.gnome.gedit.preferences.editor bracket-matching true
    - gsettings set org.gnome.gedit.preferences.editor create-backup-copy false
    - gsettings set org.gnome.gedit.preferences.editor display-line-numbers true
    - gsettings set org.gnome.gedit.preferences.editor editor-font 'Hack 10'
    - gsettings set org.gnome.gedit.preferences.editor highlight-current-line true
    - gsettings set org.gnome.gedit.preferences.editor insert-spaces true
    - gsettings set org.gnome.gedit.preferences.editor scheme 'oblivion'
    - gsettings set org.gnome.gedit.preferences.editor tabs-size "uint32 4"
    - gsettings set org.gnome.gedit.preferences.editor use-default-font false
    - gsettings set org.gnome.gedit.preferences.editor wrap-mode 'none'

- name: Set Calc preferences
  command: "{{ item }}"
  with_items:
    - gsettings set org.gnome.calculator accuracy 8
    - gsettings set org.gnome.calculator button-mode 'advanced'
    - gsettings set org.gnome.calculator number-format 'fixed'
    - gsettings set org.gnome.calculator source-units 'EUR'
    - gsettings set org.gnome.calculator target-units 'USD'
