---
- hosts: all

  pre_tasks:
    - import_tasks: tasks/users.yml
      tags: users

  tasks:
  - import_tasks: tasks/general.yml
    tags: general

  - import_tasks: tasks/jujhar-apt-software.yml
    tags: my-software

- name: Ubuntu desktop environment playbook
  hosts: all
  roles:
    #- { role: arc-theme, become: true }
    #- { role: chromium, become: true }
    #- { role: dbeaver, become: true }
    #- { role: desktop, become: true }
    # - { role: desktop-cleanup, become: true }
    # - { role: docker, become: true }
    # - { role: filezilla, become: true }
    # - { role: firefox, become: true }
    # - { role: gimp, become: true }
    # - { role: indicator-sysmonitor, become: true }
    # - { role: libreoffice, become: true }
    # - { role: mysql-workbench, become: true }
    # - { role: min, become: true }
    # - { role: nautilus-plugins, become: true }
    # - { role: nodejs, become: true }
    # - { role: notepadqq, become: true }
    # - { role: python, become: true }
    # - { role: remmina, become: true }
    # - { role: vagrant, become: true }
    # - { role: virtualbox, become: true }
    # - { role: wine, become: true }
    # - { role: zsh, become: true }
