- name: Remove ubuntu dock
  command: apt remove -y gnome-shell-extension-ubuntu-dock

- name: Set max file watches for crashplan inotify.
  lineinfile:
    path: /etc/sysctl.conf
    line: fs.inotify.max_user_watches=1048576

- name: Install sudoers
  copy:
    dest: "/etc/sudoers.d/{{ user.username }}"
    content: "{{ user.username }} ALL=(ALL) NOPASSWD:ALL"
