galaxy_info:
  author: pixelart
  description: Install Google Chrome
  company: pixelart GmbH

  license: MIT

  min_ansible_version: 2.2

  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all

  galaxy_tags:
    - google-chrome
    - chrome
    - browser
